# Generated by Django 5.0 on 2023-12-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_remove_post_created_at_post_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Save_crawl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmp", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "product",
            },
        ),
    ]
