# Generated by Django 5.0 on 2023-12-22 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_save_crawl"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="title",
            new_name="tmp",
        ),
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
    ]
