# Generated by Django 4.1.13 on 2023-12-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0006_delete_save_crawl_remove_post_tmp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="link",
            field=models.TextField(default=""),
        ),
    ]
